import os
from dotenv import load_dotenv
from pydantic import BaseModel, Field
from langchain_mistralai import ChatMistralAI
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.output_parsers import PydanticOutputParser

# 1. Load your API keys
load_dotenv()
if not os.getenv("MISTRAL_API_KEY"):
    raise ValueError("MISTRAL_API_KEY not found! Please check your .env file.")

# 2. Define the exact data structure we want using Pydantic (The Schema)
# We tell the AI exactly what fields to look for and what data types they must be.
class MovieInfo(BaseModel):
    title: str = Field(description="The exact name of the movie")
    year: int = Field(description="The year the movie was released")
    director: str = Field(description="The full name of the director")

# 3. Set up the Pydantic Output Parser based on our schema
parser = PydanticOutputParser(pydantic_object=MovieInfo)

# 4. Initialize the Mistral model
model = ChatMistralAI(model="mistral-large-latest")

# 5. Create a Prompt Template
# We inject the parser's built-in formatting instructions into the prompt so the AI knows the rules.
prompt = ChatPromptTemplate.from_messages([
    ("system", "You are an expert data extraction algorithm. Extract information from the text.\n\n{format_instructions}"),
    ("human", "{text}")
])

# 6. Build the LCEL Chain
chain = prompt | model | parser

# 7. Test it with unstructured, conversational text
messy_text = "I absolutely loved watching Inception on an airplane. Christopher Nolan did a great job directing it back in 2010."

print("Analyzing messy text and extracting strict data...\n")

# 8. Invoke the chain
# We must pass the `format_instructions` generated by our Pydantic parser
result = chain.invoke({
    "text": messy_text,
    "format_instructions": parser.get_format_instructions()
})

# --- See the magic! ---
print("--- Extracted Pydantic Object ---")
print(f"Data Type: {type(result)}\n") # Notice this is no longer a generic string!

# Because it is a Pydantic object, we can access the data cleanly like this:
print(f"Database-ready Title: {result.title}")
print(f"Database-ready Year: {result.year}")
print(f"Database-ready Director: {result.director}")